### ISSUE TITLE
OSError: Cannot read image file. File is not an image file.

### ISSUE THREAD

**Issue by cravisjan97** [sanguinariojoe/pip-openexr#10]
I get this error: `OSError: Cannot read image file. File is not an image file.` when I run `exr_file = OpenEXR,InoutFile(<exr file path>)` for some exr files. For others it seems to work. I am not sure why this error occurs for some exr files. Can you please help me out with this?

**Comment by sanguinariojoe** [comment]
Hey!

I suppose you would say `OpenEXR.InputFile(<exr file path>)`. I am afraid your problem is with OpenEXR itself rather than with this wrapper. Look here:

https://github.com/sanguinariojoe/pip-openexr/blob/main/OpenEXR.cpp#L770

We just try to open the file using the OpenEXR library, and in case of exceptions (reported by such library) trigger an `IOError`
